// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/font-pairings/DMSansCormorant.tsx": () => import("../components/mockups/font-pairings/DMSansCormorant.tsx"),
  "./components/mockups/font-pairings/OutfitLibreBaskerville.tsx": () => import("../components/mockups/font-pairings/OutfitLibreBaskerville.tsx"),
  "./components/mockups/font-pairings/SpaceGroteskFraunces.tsx": () => import("../components/mockups/font-pairings/SpaceGroteskFraunces.tsx"),
  "./components/mockups/font-pairings/SyneInstrumentSerif.tsx": () => import("../components/mockups/font-pairings/SyneInstrumentSerif.tsx")
};
